- hosts: routers
  gather_facts: no
  connection: network_cli
  tasks:
    - ios_facts:
      register: facts

    - debug:
        msg: "My serial number: {{ ansible_net_serialnum }}"

    - debug:
        msg: "Internet's serial number: {{ hostvars['internet'].ansible_net_serialnum }}"