viptela:
  system_ip: 192.168.255.12
  transport_ip: 10.0.0.12
  org: "{{ organization_name }}"
  site_id: 1
  vbond:
    remote: 10.0.0.11

vpn_instances:
  - vpn_id: 0
    interfaces:
      - if_name: eth1
        ip:
          address: 10.0.0.12/24
        tunnel_interface: true
        allow_service:
        - all
        enabled: true
    routes:
      - prefix: 0.0.0.0/0
        next_hop:
          address: 10.0.0.1