vpn_instances:
  - vpn_id: 0
    interfaces:
      - if_name: ge0/0
        ip:
          address: 172.20.0.10/30
        tunnel_interface:
        shutdown: false
    routes:
      - prefix: 0.0.0.0/0
        next_hop:
          address: 172.20.0.9
  - vpn_id: 1
    interfaces:
      - if_name: ge0/1
        ip:
          address: 192.168.1.1/24
        shutdown: false