vpn_instances:
  - vpn_id: 0
    interfaces:
      - if_name: ge0/0
        ip:
          address: 10.0.0.13/24
        tunnel_interface:
        shutdown: false
    routes:
      - prefix: 0.0.0.0/0
        next_hop:
          address: 10.0.0.1
  - vpn_id: 1
    interfaces:
      - if_name: ge0/1
        ip:
          address: 10.0.255.6/30
        shutdown: false
    ospf:
      area: 0
      redistribute:
        - omp
      interfaces:
        - if_name: ge0/1
          hello_interval: 10
          dead_interval: 40
          retransmit_interval: 5
          priority: 1
          network: broadcast