---
- name: CONFIGURE ROUTERS
  hosts: routers
  gather_facts: no
  connection: netconf

  tasks:
    - name: ENABLE NETCONF/YANG ON THE ROUTER
      cli_config:
        config: netconf-yang

    - set_facts:
        template_file: "{{ ansible_network_os }}-ntp-netconf.j2"

    - name: ENSURE THAT THE DESIRED NTP SERVERS ARE PRESENT
      netconf_rpc:
        rpc: edit-config
        content: "{{ lookup('template', temaplate_file) }}"